obj-$(CONFIG_LTQ_STAT_HELPER) += stat_helper.o platform/stat_helper_platform.o
obj-$(CONFIG_LTQ_STAT_HELPER_XRX330) += platform/xrx330/stat_helper_xrx330.o
obj-$(CONFIG_LTQ_STAT_HELPER_XRX300) += platform/xrx300/stat_helper_xrx300.o
obj-$(CONFIG_LTQ_STAT_HELPER_XRX200) += platform/xrx200/stat_helper_xrx200.o
