obj-$(CONFIG_LTQ_DIRECTCONNECT_DP) = ltq_directconnect_datapath.o
ltq_directconnect_datapath-objs = directconnect_dp_api.o
ltq_directconnect_datapath-objs += directconnect_dp_pmac.o
ltq_directconnect_datapath-objs += directconnect_dp_wave500_api.o
ltq_directconnect_datapath-objs += directconnect_dp_wave500_sta.o
ltq_directconnect_datapath-objs += directconnect_dp_proc.o
