obj-y := prom.o sysctrl.o clk.o reset.o ltq_dma.o timer.o mtlk_init.o dcdc.o

obj-y += vmmc.o mtd_split.o

obj-$(CONFIG_PCI) += ath_eep.o rt_eep.o pci-ath-fixup.o

obj-$(CONFIG_XRX200_PHY_FW) += xrx200_phy_fw.o
