#!/bin/sh
LOGTIME=$(date "+%Y-%m-%d %H:%M:%S")

baidu_state()
{
/usr/sbin/wget -4 --spider --quiet --tries=2 --timeout=2 wap.baidu.com
if [ "$?" == "0" ]; then
	log='baidu   --- [ '$LOGTIME' ]    OK '
else
	log='baidu   --- [ '$LOGTIME' ]    NO '
fi

nvram set ss_china_state="$log"
}

google_state()
{
#这里有个bug,因为路由只能使用wan默认dns不能剔除污染,所以这里只能用支持ip访问的网站转换成ip测试
server_ip=`nslookup "facebook.com" 127.0.0.1 | sed '1,4d' | awk '{print $3}' | grep -v :|awk 'NR==1{print}'`
/usr/sbin/wget -4 --spider --quiet --tries=2 --timeout=2 $server_ip
if [ "$?" == "0" ]; then
	log=' google - [ '$LOGTIME' ]    OK '
else
	log=' google - [ '$LOGTIME' ]    NO '
fi

nvram set ss_foreign_state="$log"
}

sleep 5
baidu_state
google_state
sleep 20
baidu_state
google_state
exit 0

