#
# drivers/char/ltq_icc/Makefile
#

#
# Makefile for the Lantiq icc driver
#
obj-y += drv_icc.o icc_client.o

obj-$(CONFIG_SOC_GRX500_BOOTCORE) += proc_redirect_bootcore.o
obj-$(CONFIG_SOC_GRX500) += proc_redirect.o
