#!/bin/sh

menable=`nvram get ssr_enable 2>/dev/null`

IGNORE=/usr/sbin/ssr/ignore.list
if [ -f "/jffs/configs/ssr_user.txt" ] ;then
IGNORE2=/jffs/configs/ssr_user.txt
else
IGNORE2=/usr/sbin/ssr/ignore.user
fi
FORCE=/jffs/configs/ssr_forceip.txt
IGNORESIP=/jffs/configs/ssr_sip.txt

flush_r() {

iptables -t nat -F SHADOWSOCKS > /dev/null 2>&1
iptables -t nat -D PREROUTING -p tcp -j SHADOWSOCKS > /dev/null 2>&1
iptables -t nat -D OUTPUT -p tcp -j SHADOWSOCKS > /dev/null 2>&1
iptables -t nat -X SHADOWSOCKS > /dev/null 2>&1

ipset -F ssr >/dev/null 2>&1 && ipset -X ssr >/dev/null 2>&1
ipset -F ssr_tg >/dev/null 2>&1 && ipset -X ssr_tg >/dev/null 2>&1
ipset -F ssr_ignore >/dev/null 2>&1 && ipset -X ssr_ignore >/dev/null 2>&1

#udp
iptables -t mangle -F SS_SPEC_TPROXY 2>/dev/null 
iptables -t mangle -D PREROUTING -p udp -j SS_SPEC_TPROXY 2>/dev/null
iptables -t mangle -X SS_SPEC_TPROXY 2>/dev/null
ip rule del fwmark 1 table 100 2>/dev/null
ip route del local default dev lo table 100 2>/dev/null

return 0	
}

gen_iplist() {
	cat <<-EOF
		0.0.0.0/8
		10.0.0.0/8
		100.64.0.0/10
		127.0.0.0/8
		169.254.0.0/16
		172.16.0.0/12
		192.0.0.0/24
		192.0.2.0/24
		192.88.99.0/24
		192.168.0.0/16
		198.18.0.0/15
		198.51.100.0/24
		203.0.113.0/24
		224.0.0.0/4
		240.0.0.0/4
		255.255.255.255
		$(cat ${IGNORE2:=/dev/null} 2>/dev/null)
EOF
}

gen_iplist2() {
	cat <<-EOF
		$(cat ${IGNORE:=/dev/null} 2>/dev/null)
EOF
}


# Get argument
server=$1
local_port=$2 
if [ "$server" == "clean" ] ;then
  flush_r
  exit 0
fi



[ ! -f $IGNORE ] && echo "$IGNORE not found." && exit 1

# Check variable
[ -z $server ] || [ -z $local_port ] && {
	echo "Invalid variable, please check CONFIG."
	exit 1
}

all_proxy=`nvram get ssr_mode`
dns_mode=`nvram get ssr_dnsmode`
udp_enable=`nvram get ssr_udp_enable`

# Create a new chain
BEGIN="*nat\n\
:SHADOWSOCKS - [0:0]\n\
-I PREROUTING -p tcp -j SHADOWSOCKS\n\
-I OUTPUT 1 -p tcp -j SHADOWSOCKS\n\
-A SHADOWSOCKS -d $server/32 -j RETURN\n\
-A SHADOWSOCKS -d 0.0.0.0/8 -j RETURN\n\
-A SHADOWSOCKS -d 10.0.0.0/8 -j RETURN\n\
-A SHADOWSOCKS -d 127.0.0.0/8 -j RETURN\n\
-A SHADOWSOCKS -d 169.254.0.0/16 -j RETURN\n\
-A SHADOWSOCKS -d 172.16.0.0/12 -j RETURN\n\
-A SHADOWSOCKS -d 192.168.0.0/16 -j RETURN\n\
-A SHADOWSOCKS -d 224.0.0.0/4 -j RETURN\n\
-A SHADOWSOCKS -d 240.0.0.0/4 -j RETURN\n\
"

ipset -! create ssr nethash && ipset flush ssr
ipset -! create ssr_tg nethash && ipset flush ssr_tg
if [ "$dns_mode" = "1" ] ;then
 cp -f /usr/sbin/ssr/gfw_list.conf /tmp/etc/dnsmasq.user/gfw_list.conf
 if [ -f "/jffs/configs/ssr_gfw.txt" ] ;then
  icount=`cat /jffs/configs/ssr_gfw.txt|grep .|wc -l`
  if [ $icount -gt 0 ] ;then
   sed '/.*/s/.*/server=\/&\/127.0.0.1#1053\nipset=\/&\/ssr/' /jffs/configs/ssr_gfw.txt > /tmp/etc/dnsmasq.user/gfw_user.conf
  else
		[ -f "/tmp/etc/dnsmasq.user/gfw_user.conf" ] && rm -f /tmp/etc/dnsmasq.user/gfw_user.conf
  fi
 fi
else
 cp -f /usr/sbin/ssr/gfw_addr.conf /tmp/etc/dnsmasq.user/gfw_addr.conf
 if [ -f "/jffs/configs/ssr_gfw.txt" ] ;then
  icount=`cat /jffs/configs/ssr_gfw.txt|grep .|wc -l`
  if [ $icount -gt 0 ] ;then
   sed '/.*/s/.*/address=\/&\/93.46.8.89/' /jffs/configs/ssr_gfw.txt > /tmp/etc/dnsmasq.user/gfw_user.conf
  else
		[ -f "/tmp/etc/dnsmasq.user/gfw_user.conf" ] && rm -f /tmp/etc/dnsmasq.user/gfw_user.conf
  fi
 fi
fi

service restart_dnsmasq



/usr/sbin/ssr/ssr_mon.sh &



if [ "$all_proxy" = "1" ] ;then

ip_gfw="208.67.222.222 208.67.220.220 8.8.8.8 8.8.4.4"
for ip in $ip_gfw
do
	ipset -! add ssr $ip 2>/dev/null
done

ip_tg="149.154.0.0/16 91.108.4.0/22 91.108.56.0/24 109.239.140.0/24 67.198.55.0/24 "
for ip in $ip_tg
do
	ipset -! add ssr_tg $ip 2>/dev/null
done

if [ "$dns_mode" = "1" ] ;then
echo -e "$BEGIN\
-A SHADOWSOCKS  -p tcp -m set --match-set ssr dst  -j REDIRECT --to-ports $local_port\n\
-A SHADOWSOCKS  -p tcp -m set --match-set ssr_tg dst  -j REDIRECT --to-ports $local_port\n\

COMMIT" | iptables-restore -n
else
echo -e "$BEGIN\
-A SHADOWSOCKS  -p tcp -d 93.46.8.89/32  -j REDIRECT --to-ports $local_port\n\
-A SHADOWSOCKS  -p tcp -m set --match-set ssr_tg dst  -j REDIRECT --to-ports $local_port\n\

COMMIT" | iptables-restore -n
fi

if [ -f "$FORCE" ] ;then
sed "/.*/s/.*/iptables -t nat -A SHADOWSOCKS  -p tcp -d & -j REDIRECT --to-ports $local_port  /" $FORCE  2>/dev/null | sh
fi

#udp
if [ "$udp_enable" == "1" ] ;then
	ip rule add fwmark 1 table 100
	ip route add local default dev lo table 100
	iptables -t mangle -N SS_SPEC_TPROXY
	if [ "$dns_mode" = "1" ] ;then
	iptables -t mangle -A SS_SPEC_TPROXY -p udp -m set  --match-set ssr dst \
		-j TPROXY --on-port $local_port --tproxy-mark 0x01/0x01
	else
	iptables -t mangle -A SS_SPEC_TPROXY -p udp -d 93.46.8.89/32 \
		-j TPROXY --on-port $local_port --tproxy-mark 0x01/0x01
	fi
fi

exit 0
fi


ipset -! create ssr_ignore nethash && ipset flush ssr_ignore
echo -e "$BEGIN\n\
-A SHADOWSOCKS -m set --match-set ssr_ignore dst -j RETURN \n\
-A SHADOWSOCKS -p tcp  -j REDIRECT --to-ports $local_port\n\
COMMIT" | iptables-restore -n

if [ -f "$IGNORESIP" ] ;then
sed "/.*/s/.*/iptables -t nat -I SHADOWSOCKS  -p tcp -s & -j RETURN  /" $IGNORESIP  2>/dev/null | sh
fi

# Read the ignore list

if [ "$all_proxy" = "2" ] ;then
ipset -! -R <<-EOF || return 1
$(gen_iplist | sed -e "s/^/add ssr_ignore /")
EOF
else
ipset -! -R <<-EOF || return 1
$(gen_iplist | sed -e "s/^/add ssr_ignore /")
$(gen_iplist2 | sed -e "s/^/add ssr_ignore /")
EOF
fi

#udp
if [ "$udp_enable" == "1" ] ;then
	ip rule add fwmark 1 table 100
	ip route add local default dev lo table 100
	iptables -t mangle -N SS_SPEC_TPROXY

	iptables -t mangle -A SS_SPEC_TPROXY -p udp -m set ! --match-set ssr_ignore dst \
		-j TPROXY --on-port $local_port --tproxy-mark 0x01/0x01

	iptables -t mangle  -I PREROUTING 1 -p udp  -j SS_SPEC_TPROXY
fi
exit 0

